from collections import OrderedDict

dictionary = {
    "3 River Wireless": "@sms.3rivers.net",
    "ACS Wireless": "@paging.acswireless.com",
    "AT&T": "@txt.att.net",
    "Bell Mobility": "@txt.bellmobility.ca",
    "Boost Mobile": "@myboostmobile.com",
    "Cellular One": "@mobile.celloneusa.com",
    "Cellular South": "@csouth1.com",
    "Centennial Wireless": "@cwemail.com",
    "Cingular (Now AT&T)": "@txt.att.net",
    "Clearnet": "@msg.clearnet.com",
    "Comcast": "@comcastpcs.textmsg.com",
    "Corr Wireless Communications": "@corrwireless.net",
    "Fido": "@fido.ca",
    "Golden Telecom": "@sms.goldentele.com",
    "Helio": "@messaging.sprintpcs.com",
    "Houston Cellular": "@text.houstoncellular.net",
    "Rogers Canada": "@pcs.rogers.com",
    "Metro PCS": "@mymetropcs.com",
    "President's Choice": "@txt.bell.ca",
    "Public Service Cellular": "@sms.pscel.com",
    "Rogers AT&T Wireless": "@pcs.rogers.com",
    "Southwestern Bell": "@email.swbw.com",
    "T-Mobile": "@tmomail.net",
    "US West": "@uswestdatamail.com",
    "Virgin Mobile": "@vmobl.com",
    "Western Wireless": "@cellularonewest.com",
    "Tracfone": "@txt.att.net",
    "Carolina West Wireless": "er@cwwsms.com",
    "Virgin Mobile Canada": "@vmobile.ca",
    "Qwest": "@qwestmp.com",
    "Metrocall": "@page.metrocall.com",
    "Verizon": "@vtext.com",
    "BPL Mobile": "@bplmobile.com",
    "Triton": "@tms.suncom.com",
    "Surewest Communicaitons": "@mobile.surewest.com",
    "MTS": "@text.mtsmobility.com",
    "Alltel": "@message.alltel.com",
    "Bell Mobility (Canada)": "@txt.bell.ca",
    "Unicel": "@utext.com",
    "Inland Cellular Telephone": "@inlandlink.com",
    "Solo Mobile": "@txt.bell.ca",
    "CenturyTel": "@messaging.centurytel.net",
    "Bell Canada": "@bellmobility.ca",
    "Idea Cellular": "@ideacellular.net",
    "Sprint": "@messaging.sprintpcs.com",
    "Illinois Valley Cellular": "@ivctext.com",
    "Metrocall 2-way": "@my2way.com",
    "US Cellular": "@email.uscc.net",
    "Satellink": ".pageme@satellink.net",
    "Dobson": "@mobile.dobson.net",
    "Edge Wireless": "@sms.edgewireless.com",
    "Nextel": "@messaging.nextel.com",
    "MCI": "@pagemci.com",
    "Microcell": "@fido.ca",
    "OnlineBeep": "@onlinebeep.net",
    "PCS One": "@pcsone.net",
    "Sumcom": "@tms.suncom.com",
    "Telus": "@msg.telus.com",
    "Blue Sky Frog": "@blueskyfrog.com",
    "West Central Wireless": "@sms.wcc.net",
    "Mobilcomm": "@mobilecomm.net",
    "Bluegrass Cellular": "@sms.bluecell.com",
    "Midwest Wireless": "@clearlydigital.com",
}

CARRIERS = OrderedDict(sorted(dictionary.items()))
CARRIER_CHOICES = ((CARRIERS[item][:4], item) for item in CARRIERS.keys())
